import { StyleSheet } from 'react-native';
import { Colors, Space, Radius, Font } from '../../theme';

const styles = StyleSheet.create({
  // Top bar
  topBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: Space.lg,
  },
  topLeft: { flexDirection: 'row', alignItems: 'center', gap: Space.sm },
  topRight: { flexDirection: 'row', gap: Space.sm },
  avatarWrap: { position: 'relative' },
  avatar: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: Colors.gold,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: { fontSize: 12, fontWeight: '800', color: Colors.textInverse },
  avatarBadge: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#3DCB7F',
    borderWidth: 1.5,
    borderColor: Colors.bg,
  },
  aiProtectedPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: Radius.full,
    backgroundColor: 'rgba(61,203,127,0.08)',
    borderWidth: 0.5,
    borderColor: 'rgba(61,203,127,0.25)',
  },
  aiProtectedText: {
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.8,
    color: '#3DCB7F',
  },
  iconBtn: {
    width: 36,
    height: 36,
    borderRadius: Radius.sm,
    backgroundColor: Colors.bgCard,
    borderWidth: 0.5,
    borderColor: Colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  notifBadge: {
    position: 'absolute',
    top: 7,
    right: 7,
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: Colors.gold,
    borderWidth: 1.5,
    borderColor: Colors.bg,
  },

  // Greeting
  greetingBlock: { marginBottom: Space.xl },
  greetingSub: { ...Font.labelS, color: Colors.gold, letterSpacing: 1.5 },
  greetingName: {
    ...Font.displayXL,
    color: Colors.textPrimary,
    fontSize: 30,
    fontWeight: '300',
    marginTop: 2,
  },
  greetingDesc: { ...Font.bodyS, color: Colors.textSecondary, marginTop: 4 },

  // Hero card
  heroCard: {
    backgroundColor: Colors.bgCard,
    borderRadius: Radius.xl,
    borderWidth: 0.5,
    borderColor: Colors.border,
    padding: Space.xl,
    marginBottom: Space.md,
  },
  heroLabel: {
    ...Font.labelS,
    color: Colors.textMuted,
    marginBottom: Space.md,
  },
  heroAmountRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 3,
    marginBottom: Space.sm,
  },
  heroCurrency: {
    fontSize: 20,
    fontWeight: '300',
    color: Colors.textSecondary,
    marginBottom: 6,
  },
  heroAmount: {
    ...Font.numXL,
    color: Colors.textPrimary,
    fontSize: 44,
    fontWeight: '300',
    letterSpacing: -1.5,
  },
  heroDecimal: {
    fontSize: 22,
    fontWeight: '300',
    color: Colors.textSecondary,
    marginBottom: 6,
  },
  heroMetaRow: { flexDirection: 'row', gap: Space.sm, marginBottom: Space.lg },
  heroChangePill: {
    paddingHorizontal: Space.md,
    paddingVertical: 4,
    borderRadius: Radius.full,
    backgroundColor: 'rgba(61,203,127,0.1)',
    borderWidth: 0.5,
    borderColor: 'rgba(61,203,127,0.3)',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  heroChangePillText: { fontSize: 11, fontWeight: '600', color: '#3DCB7F' },
  heroBudgetPill: {
    paddingHorizontal: Space.md,
    paddingVertical: 4,
    borderRadius: Radius.full,
    backgroundColor: Colors.goldMuted,
    borderWidth: 0.5,
    borderColor: Colors.goldBorder,
  },
  heroBudgetPillText: { fontSize: 11, fontWeight: '600', color: Colors.gold },
  heroStatRow: {
    flexDirection: 'row',
    borderTopWidth: 0.5,
    borderTopColor: Colors.border,
    paddingTop: Space.lg,
    marginBottom: Space.lg,
  },
  heroStat: { flex: 1, alignItems: 'center' },
  heroStatBorder: { borderRightWidth: 0.5, borderRightColor: Colors.border },
  heroStatLabel: {
    ...Font.labelS,
    color: Colors.textMuted,
    fontSize: 9,
    marginBottom: 4,
  },
  heroStatVal: { ...Font.labelL, color: Colors.textPrimary, fontSize: 15 },
});

export default styles;